<?php
$translate = $this->plugin('translate');
$searchType = $this->siteSetting('search_type', 'sitewide');
switch ($searchType) {
    case 'cross-site':
        $searchAction = $this->url('site/cross-site-search', ['action' => 'results'], true);
        break;
    case 'sitewide':
    default:
        $searchAction = $this->url('site/resource', ['controller' => 'index', 'action' => 'search'], true);
}
//$searchValue = $this->escapeHtml($this->params()->fromQuery('property', ''));
$searchValues = $this->params()->fromQuery('property', '');
$searchValue = "";
if($searchValues){
    foreach ($searchValues as $e){
        if($e["property"] == "" and $e["type"] == "in"){
            $searchValue = $e["text"];
            break;
        }
    }
}
?>
<!--
<form action="<?php echo $this->escapeHtml($searchAction); ?>" id="search-form" class="input-group">
    <input type="text" name="fulltext_search" value="<?php echo $searchValue; ?>"
        placeholder="<?php echo $translate('Search'); ?>"
        aria-label="<?php echo $translate('Search'); ?>" class="input-group-field">
    <div class="input-group-button">
    <button type="submit" class="button"><?php echo $translate('Search'); ?></button>
    </div>
</form>
-->
<form action="<?php echo $this->escapeHtml($this->url('site/resource', ['controller' => 'item','action' => 'browse'], true)); ?>" id="search-form" class="input-group">
    <input type="text" name="property[0][text]" value="<?php echo $searchValue; ?>"
        placeholder="<?php echo $translate('Search'); ?>"
        aria-label="<?php echo $translate('Search'); ?>" class="input-group-field">
        <input type="hidden" name="property[0][joiner]" value="and" />
    <input type="hidden" name="property[0][property]" value="" />
    <input type="hidden" name="property[0][type]" value="in" />
    <div class="input-group-button">
    <button type="submit" class="button"><?php echo $translate('Search'); ?></button>
    </div>
</form>
